<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="RLI_CHECK"
    errors="0" failures="1" hostname="" id="" package="RLI_CHECK" skipped="0"
    tests="3" time="83.63" timestamp="">
  
    <testcase name="loginfind" classname="RLI_CHECK" time="25.57" assertions="5">

    

    

    

    

    
    </testcase>
  
    <testcase name="Pencil edit" classname="RLI_CHECK" time="6.181" assertions="1">

    
    </testcase>
  
    <testcase name="On pencil Select Lost sales stage and verify if Lost category is displayed" classname="RLI_CHECK" time="51.87" assertions="4">

    

    

      <failure message="Timed out while waiting for element &lt;#Opportunities &gt; div.record.oppty-main-tab.oppty-css-fix &gt; div.record-main-tab &gt; div &gt; div:nth-child(2) &gt; div &gt; div:nth-child(2) &gt; div &gt; span.normal.index &gt; span &gt; div &gt; span:nth-child(1) &gt; div&gt; to be present for 40000 milliseconds. - expected [0;32m&#34;visible&#34;[0m but got: [0;31m&#34;not found&#34;[0m">    at Object.On pencil Select Lost sales stage and verify if Lost category is displayed (/Users/gowdham/Documents/Node/DataFlowAutomation/tests/RLI_CHECK.js:30:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    <failure message="    at Object.On pencil Select Lost sales stage and verify if Lost category is displayed (/Users/gowdham/Documents/Node/DataFlowAutomation/tests/RLI_CHECK.js:30:8)">    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
